Homework2
made-ml-in-prod-2021/mikhail.gashkov pull request #3
Opened 2021-05-19 15:51 UTC by MikhailYeka

2021-05-24 08:03 UTC, Mikhail-M requested changes
удалите *.pyc

2021-05-24 08:45 UTC, ainureg commented
Докерфайл адекватен, хоть и не корректен. Думаю, за это можно один бал добавить. У нас же каждое задание не строго между нулем и полным баллом?

В остальном согласен с самооценкой. Работа хорошая.

2021-05-26 15:58 UTC, MikhailYeka commented
Удалил __pycache__

2021-05-26 15:59 UTC, MikhailYeka commented
@ainureg Спасибо за ревью. Можете ли порекомендовать хорошее руководство по написанию Dockerfile'ов? Буду очень благодарен

2021-05-26 16:04 UTC, ainureg approved these changes

2021-05-27 17:32 UTC, ainureg commented
> @ainureg Спасибо за ревью. Можете ли порекомендовать хорошее руководство по написанию Dockerfile'ов? Буду очень благодарен
@MikhailYeka  Зачем на Вы?) Я же такой ученик, твой коллега :)

Мне повезло, я по работе много работал с доккерами. Вообще учитывая мои знания, то лекция от Михаила мне кажется основательной. От себя могу только напомнить про степик, https://stepik.org/course/74010/promo. Курс достаточно плюшевый, но кажется большего и не надо

2021-05-28 10:37 UTC, MikhailYeka commented
Спасибо за наводку, посмотрю👍 Я пока докеры только готовые использовал, надо бы конечно углубить свои знания в этом.

2021-05-29 12:05 UTC, MikhailYeka commented
Напишите, когда можно будет мерджить пожалуйста

2021-06-02 15:40 UTC, MikhailYeka reviewed
Deleted *.pyc

2021-06-06 10:03 UTC, Mikhail-M approved these changes
Баллы: 12

Можно будет посмотреть оч много работ от коллег по соседству, чтобы прокачаться в докере, а так сам код норм написан

2021-06-06 16:24 UTC, merged